version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/infraagent
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./terraform:/app/terraform
      - ./mcp:/app/mcp

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - app

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: infraagent
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
